### ISSUE TITLE
Request for sharing epinions and slashdot datasets used

### ISSUE THREAD

**Issue by atalnarayan** [huangjunjie95/SiGAT#1]
Hi,
Can you please share the train-test split that you used for slashdot and epinions datasets? If not, then can you at least mention how you did the splitting?

**Comment by h12345jack** [comment]
Hello, 
As I mentioned in the paper, these datasets are split by 5-fold cross-validation experiments on the edge lists.

**Comment by huangjunjie-cs** [comment]
Hello,
As I mentioned in the paper, these datasets are split by 5-fold cross-validation experiments on the edge lists.

Dataset Links:
http://snap.stanford.edu/data/soc-sign-epinions.html
http://snap.stanford.edu/data/soc-sign-Slashdot090221.html

**Comment by atalnarayan** [comment]
Thanks!
